### ISSUE TITLE
Chunks not getting saved in the required location?

### ISSUE THREAD

**Issue by varunasingh** [mrawdon/resumable-node#1]
Files uploaded are not being saved to the required directory but the chunks all fo to /tmp/ instead.

**Comment by mrawdon** [comment]
How are you calling it?  It seems to be working fine for me.  

You should call it as 
var resumable = require('resumable-node')('/path/to/your/temp');

I'm not crazy about the way its being passed in now.  But that's how the sample code was written, so if you have any suggestions let me know.

**Comment by varunasingh** [comment]
Hey, So I JUST figured it out. It wasnt so obvious to me, but basically resumable-node.js wants so:
 module.exports = resumable = function(temporaryFolder, useSubDirectories) 
Take a note of useSubDirectories 
Now, when you upload a file say : blah.txt 
It will store chunks in /path/to/your/temp/randomid-blahtxt/ 

This means subDirectories is by default used as per the sample and resumable-node.js 
Which means: it is checked here:

 $.getChunkPath = function(identifier){
          if(useSubDirectories){
                return path.join($.temporaryFolder, cleanIdentifier(identifier));
          }
          else{
                  return $.temporaryFolder;
          }
  }

And then called here: 
 var chunkFilePath = $.getChunkPath(identifier);
        fs.exists(chunkFilePath, function(exists){
                if(!exists){
                        console.log("!The path: " + chunkFilePath + " does not exist!");
                        return fs.mkdir(chunkFilePath, function(success){
                                $.post(req, callback);
                        });
                }

That part of the code above will only be allowed if useSubDirectories is set. 

SO, the way to call it would be something like: 

var resumable = require('resumable-node')('/path/to/your/temp', 'True') 

True is just a string here, can be anything, basically it is set and not "undefied". Hope that makes sense. Let me know what you think.

**Comment by varunasingh** [comment]
Basically, fs.rename ('from-file.txt' , '/to-folder/to-file.txt') wont work until /to-folder/ is created as per fs.rename spec. 
Thats basically what 
var chunkFilePath = $.getChunkPath(identifier);
fs.exists(chunkFilePath, function(exists){
if(!exists){
console.log("!The path: " + chunkFilePath + " does not exist!");
return fs.mkdir(chunkFilePath, function(success){
$.post(req, callback);
});
} 
is doing.

**Comment by mrawdon** [comment]
Yeah that makes sense. I'm on vacation this week so I'm not sure when I can
look at it. If you send over a pull request I can accept it
